/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlybangiay_1;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class CART extends javax.swing.JFrame {
	Database db = new Database();

	/**
	 * Creates new form SALE
	 */
	public CART() {
		initComponents();

		// chen vo table
		reloadCart();
	}

	void reloadCart() {
		DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
		int rowCount = model.getRowCount();
		for (int i = rowCount - 1; i >= 0; i--) {
			model.removeRow(i);
		}
		ResultSet rs = db.getCart();
		try {
			while (rs.next()) {
				model.addRow(new Object[] { rs.getInt("MaSanPham"), rs.getString("TenSanPham"),
						rs.getInt("SoLuong"), rs.getInt("DonGia") });
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// @SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel9 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		btnCheckOut = new javax.swing.JButton();
		btnDelete = new javax.swing.JButton();
		btnBackToShop = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tblCart = new javax.swing.JTable();

		jLabel9.setText("jLabel7");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(860, 585));

		jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 153, 153));
		jLabel1.setText("KING Sneaker");
		jLabel1.setToolTipText("");

		btnCheckOut.setBackground(new java.awt.Color(255, 102, 0));
		btnCheckOut.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
		btnCheckOut.setForeground(new java.awt.Color(255, 255, 255));
		btnCheckOut.setText("CHECKOUT");
		btnCheckOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
		btnCheckOut.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnCheckOutMouseClicked(evt);
			}
		});
		btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCheckOutActionPerformed(evt);
			}
		});

		btnDelete.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
		btnDelete.setForeground(new java.awt.Color(0, 153, 153));
		btnDelete.setText("DELETE");
		btnDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
		btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnDeleteMouseClicked(evt);
			}
		});

		btnBackToShop.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
		btnBackToShop.setForeground(new java.awt.Color(0, 153, 153));
		btnBackToShop.setText("BACK TO SHOP");
		btnBackToShop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
		btnBackToShop.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnBackToShopMouseClicked(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
		jLabel2.setText("CART");

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("Copyright © 2022 King Sneaker. All rights reserved.  ");
		jLabel3.setMinimumSize(new java.awt.Dimension(100, 16));

		tblCart.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				},
				new String[] {
						"Mã sản phẩm ", "Tên sản phẩm", "Số lượng", "Đơn giá"
				}) {
			boolean[] canEdit = new boolean[] {
					false, false, false, true
			};

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane2.setViewportView(tblCart);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(17, 17, 17)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel1)
												.addGap(167, 167, 167))
										.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jSeparator1)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(btnCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(btnBackToShop,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addContainerGap())
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel2)
												.addGap(0, 0, Short.MAX_VALUE))))
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(17, 17, 17)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGap(14, 14, 14)
								.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(26, 26, 26)
												.addComponent(btnBackToShop, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														203, Short.MAX_VALUE)
												.addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
												Short.MAX_VALUE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnDeleteMouseClicked
		int result = JOptionPane.showConfirmDialog(null,
				"Bạn có muốn xoá khỏi giỏ hàng không?", "Thông báo!", JOptionPane.YES_NO_OPTION);
		if (result == JOptionPane.YES_OPTION && tblCart.getSelectedRow() > -1) {
			int a = db.deleteCart((int) tblCart.getValueAt(tblCart.getSelectedRow(), 0));
			reloadCart();
			System.out.println(a);
		}
	}// GEN-LAST:event_btnDeleteMouseClicked

	private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCheckOutActionPerformed
	}// GEN-LAST:event_btnCheckOutActionPerformed

	private void btnBackToShopMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnBackToShopMouseClicked
		SHOP shop = new SHOP();
		shop.setResizable(false);
		shop.setLocationRelativeTo(null);
		shop.setVisible(true);
		shop.setDefaultCloseOperation(HomePage.DISPOSE_ON_CLOSE);
		this.setVisible(false);
	}// GEN-LAST:event_btnBackToShopMouseClicked

	private void btnCheckOutMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCheckOutMouseClicked
		int result = JOptionPane.showConfirmDialog(null,
				"Bạn có muốn thanh toán không?", "Thông báo!", JOptionPane.YES_NO_OPTION);
		if (result == JOptionPane.YES_OPTION)
			if (db.addInvoice()) {
				INVOICE invoice = new INVOICE();
				invoice.setResizable(false);
				invoice.setLocationRelativeTo(null);
				invoice.setVisible(true);
				invoice.setDefaultCloseOperation(HomePage.DISPOSE_ON_CLOSE);
				this.setVisible(false);
			}
	}// GEN-LAST:event_btnCheckOutMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel.
		 * For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CART.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CART.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CART.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CART.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CART().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBackToShop;
	private javax.swing.JButton btnCheckOut;
	private javax.swing.JButton btnDelete;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTable tblCart;
	// End of variables declaration//GEN-END:variables
}
